version: "3.7"

services:
  app:
    image: node:14-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: rnt123
      MYSQL_DB: find_pet

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - find-pet_mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rnt123
      MYSQL_DATABASE: find_pet
      TZ: Asia/Seoul

volumes:
  find-pet_mysql-data: